name: "Terraform_S3_Bucket_Destroy"
on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest
    env : 
      working-directory  : ./S3_Bucket with Github Action

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_S3 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_S3 }}
          aws-session-token : '${{ secrets.AWS_SESSION_TOKEN_S3 }}'
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize Terraform
        run: terraform init
        working-directory : ${{ env.working-directory}}

      - name: Destroy S3 bucket
        run: terraform destroy -auto-approve
        working-directory : ${{ env.working-directory}}