name : "Terraform_S3_Bucket_Apply"

on:
   # For Manual Trigger
  workflow_dispatch:  
  
jobs:
        
  init-command-run: 
     runs-on : ubuntu-latest
     env : 
      working-directory  : ./S3_Bucket with Github Action
     steps:
     - uses: actions/checkout@v3

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
          aws-access-key-id : '${{ secrets.AWS_ACCESS_KEY_S3 }}'
          aws-secret-access-key : '${{ secrets.AWS_SECRET_KEY_S3 }}'
          aws-session-token : '${{ secrets.AWS_SESSION_TOKEN_S3 }}'
          aws-region: us-east-1
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v2
     - name : Terraform Init
       run : terraform init
       working-directory : ${{ env.working-directory}}
     - name : Terraform Plan
       run : terraform plan
       working-directory : ${{ env.working-directory}}
         
         
  apply-command-run: 
     if: ${{ always() }}
     needs : init-command-run
     runs-on : ubuntu-latest
     env : 
      working-directory  : ./S3_Bucket with Github Action
     steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id : '${{ secrets.AWS_ACCESS_KEY_S3 }}'
          aws-secret-access-key : '${{ secrets.AWS_SECRET_KEY_S3 }}'
          aws-session-token : '${{ secrets.AWS_SESSION_TOKEN_S3 }}'
          aws-region: us-east-1

      - name : Terraform Init
        run : terraform init
        working-directory : ${{ env.working-directory}}
      - name : Terraform Apply
        run : terraform apply -auto-approve
        working-directory : ${{ env.working-directory}}
